In [47]:
import numpy as np

import matplotlib.pyplot as plt


- Create the following matrix in Python  and assign it to $x3$ 


 \begin{bmatrix}
    1 & 2 & 3 & 4 & 5 \\
    6 & 7 & 8 & 9 & 10 
  \end{bmatrix}



In [27]:
#enter your code here
x3 =  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

- Determine the size of $x3$

In [3]:
np.shape(x3)

(2, 5)

- If we use `np.size(x3)` what result would we obtain?

In [28]:
#enter your code here
np.size(x3)

10

_Problem_: Here is something different I want you to think about.  If I run the following code it generates a vector **x1**,

`x1 = np.linspace(1,6,6)`

- How many elements are in _x1_.
- Write a code to access the first element in _x1_.
- Write a code to access the last element in _x1_.

In [30]:
x1 = np.linspace(1,6,6)
print(x1)

[1. 2. 3. 4. 5. 6.]


- How many elements are in x1?

In [6]:
print(len(x1))

6


In [7]:
print(np.size(x1))

6



- Write a code to access the first element in *x1*.


In [8]:
print(x1[0])

1.0


- Write a code to access the last element in *x1*.

In [9]:
x1[5]

6.0

- Given the following vector $x$, extract the numbers that satisfy the condition $2\leq x \leq 9$

In [39]:
x = np.linspace(0,10,11)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
x[2:10]

array([2., 3., 4., 5., 6., 7., 8., 9.])

For the above code, 
- 2 states that we start at second element in the list, don't forget  that the slicing index starts at 0
- 10 states that we end at the 10th element in the list, but not include it. 
- The colon in the middle states that we want to use slicing to get objects in the list

In [12]:
#How about the following code?
x[2:11]

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
#How about the following code?
x[1:11:2]

array([1., 3., 5., 7., 9.])

In [14]:
#How about the following code?
x[::-1]

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.])

Note that in the above
- Since there is no value before the first colon, it will start at the beginning index of the list. 

- Since there is no value after the first colon, it will go all the way to the end of the list.

- $-1$ makes the index to increment every time by -1, causing it to traverse the list by going backwards. 

Given that `xnew = [1, 2, 3, 4]`, write a code to sum the numbers in `xnew`.

In [42]:
xnew = [1, 2, 3, 4]
sum1 = np.sum(xnew)
print(sum1) 

10


In [44]:
#you can also use the following code to sum
sum2 = sum(xnew)
print(sum2)

10


#### Example: Finding the slope of a line. 
Given the equation  $y = 5x$, plot the graph for $0 \leq x \leq 10$ and write a code to determine the slope.

In [52]:
#Enter your code here
xval = np.linspace(0,10,11)
print(xval)
yval = 5*xval
print(yval)

slope = (yval[1]-yval[0])/(xval[1]-xval[0])
print(slope)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
5.0


In [61]:
#Here is an alternative code for finding the slope 
xval = np.linspace(0,10,11)
yval = 5*xval

nvals = xval.size 

slopes = (yval[1:nvals] - yval[0:nvals-1])/ (xval[1:nvals] - xval[0:nvals-1])

print(np.min(slopes))
print(np.max(slopes))
print(np.mean(slopes))

print(slopes)

5.0
5.0
5.0
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
